### ISSUE TITLE
Potentially move away from Dongbat Pathfinding.

### ISSUE THREAD

**Issue by Darklit** [OpenATBP/OpenATBP#28]
The dongbat pathfinding package constantly gives internal index out of bounds errors, comprising of numerous errors likely compromising the game server.

We should look at removing the path finding or trying to supplement the package with something else.

**Comment by L401** [comment]
Would it not be a good idea to just write your own implementation of the A* pathfinding algorithm?

**Comment by Darklit** [comment]
That's exactly what I did :)
